### PR TITLE
Bump to 3.30

### PR DESCRIPTION
**Pull request by bilelmoussaoui**

### CODE REVIEW

**Comment by TingPing** [comment]
bot, build

**Comment by hadess** [comment]
Was missing `"config-opts": [ "--enable-nss" ],` for liboauth, and disabling g-i in gom to make it not install an override in `/usr/` (which we won't use anyway) to fix the build.

**Comment by hadess** [comment]
And merged manually. Thanks!

**Comment by bilelmoussaoui** [comment]
Perfect, this one can be closed?

**Pull request closed without merging**
