### PR TITLE
Update runtime to GNOME 42

### PR DESCRIPTION
**Pull request by A6GibKm**

### CODE REVIEW

**Comment by hadess** [comment]
Ideally, this single commit would be 3 separate commits, and be made against https://github.com/flathub/org.gnome.Totem.Devel instead, so we could get some testing done in the wild before releasing this.

**Comment by A6GibKm** [comment]
Ok, will do that but only in two commits. Removing libhandy has to go with the runtime update.

**Comment by hadess** [comment]
> Ok, will do that but only in two commits. Removing libhandy has to go with the runtime update.

Could you try removing libhandy *after* the runtime update?

**Comment by hadess** [comment]
I'll close this PR, as it's getting a bit messy here.

**Pull request closed without merging**
